Добавил работу с репозиториями и контроллер для новостей
gof-otus/gof-project pull request #2
Opened 2023-08-20 10:35 UTC by bunnysband

2023-08-20 12:43 UTC, RyT-13 requested changes

2023-08-20 12:43 UTC, RyT-13 commented on Finik/Finik.Contracts/NewsDto.cs
> +    public DateTime CreatedDate { get; set; }
В названиях переменных лучше не дублировать их типы... для ДатаТайм можно писать суфикс At: CreatedAt, UpdatedAt ...

Ну и ко всем остальным ДатаТаймам это относится

2023-08-20 12:43 UTC, RyT-13 commented on Finik/Finik.Core/Abstractions/Services/INewsManager.cs
> +    public Task<IEnumerable<NewsDto>> GetAllNewsAsync();
Возвращать в методах IEnumerable - это зло) Особенно в публичных апи...
Принимать IEnumerable как параметр метода - это хорошо, а возвращать плохо. Нужно возвращать максимально конкретный тип (а лучше его абстракцию). Тут больше подойдет IReadOnlyList<> (но на крайний случай можно просто IList вернуть)

2023-08-20 12:43 UTC, RyT-13 commented on Finik/Finik.DbData/INewsDbRepository.cs
> +    public Task<IEnumerable<News>> GetAllNewsAsync();
*Тоже про возвращаемый IEnumerable

2023-08-20 12:43 UTC, RyT-13 commented on Finik/Finik.EfData/Repositories/NewsEfRepository.cs
> +        var newValue = await _dbContext.Set<News>().AddAsync(news);
Тут можно обойтись без создания объекта Set. Просто _dbContext.News.AddAsync()

2023-08-20 12:43 UTC, RyT-13 commented on Finik/Finik.EfData/Repositories/NewsEfRepository.cs
> +        var newsToUpdate = await _dbContext.Set<News>().Include(n => n.Author).SingleOrDefaultAsync(n => n.NewsId == news.NewsId);
Не совсем понял, зачем тут получили newToUpdate, но дальше нигде не использовали...

2023-08-20 12:43 UTC, RyT-13 commented on Finik/Finik.Models/News.cs
> +    public int NewsId { get; set; }
Нет смысла в классе News для поля Id указывать префикс News... можно просто Id

2023-08-20 12:43 UTC, RyT-13 commented on Finik/Finik.Web/Controllers/NewsController.cs
> +        public async Task<IEnumerable<NewsDto>> Get()
В контроллерах лучше возвращать List (или IList), не IEnumerable...
Всяким джсон сериализаторам проще работать сразу с Листами

2023-08-22 13:56 UTC, bunnysband commented on Finik/Finik.EfData/Repositories/NewsEfRepository.cs
> +        var newValue = await _dbContext.Set<News>().AddAsync(news);
Не получится так, я же в конструкторе просто DbContext передаю

2023-08-22 14:09 UTC, bunnysband commented on Finik/Finik.Contracts/NewsDto.cs
> +    public DateTime CreatedDate { get; set; }
fixed

2023-08-22 14:09 UTC, bunnysband commented on Finik/Finik.Core/Abstractions/Services/INewsManager.cs
> +    public Task<IEnumerable<NewsDto>> GetAllNewsAsync();
fixed

2023-08-22 14:09 UTC, bunnysband commented on Finik/Finik.DbData/INewsDbRepository.cs
> +    public Task<IEnumerable<News>> GetAllNewsAsync();
fixed

2023-08-22 14:12 UTC, bunnysband commented on Finik/Finik.EfData/Repositories/NewsEfRepository.cs
> +        var newsToUpdate = await _dbContext.Set<News>().Include(n => n.Author).SingleOrDefaultAsync(n => n.NewsId == news.NewsId);
fixed

2023-08-22 14:13 UTC, bunnysband commented on Finik/Finik.Models/News.cs
> +    public int NewsId { get; set; }
fixed

2023-08-22 14:13 UTC, bunnysband commented on Finik/Finik.Web/Controllers/NewsController.cs
> +        public async Task<IEnumerable<NewsDto>> Get()
fixed

2023-08-22 16:03 UTC, bunnysband commented on Finik/Finik.EfData/Repositories/NewsEfRepository.cs
> +        var newValue = await _dbContext.Set<News>().AddAsync(news);
Переделал на конкретный дб контекст

2023-08-22 16:04 UTC, RyT-13 requested changes

2023-08-22 16:04 UTC, RyT-13 commented on Finik/Finik.Web/Program.cs
> +builder.Services.AddScoped<DbContext, FinikDbContext>();
Здесь Скоп для контекста можно убрать... Такой же скоп создается ниже в AddDbContext<>

2023-08-22 16:04 UTC, RyT-13 commented on Finik/Finik.EfData/Repositories/NewsEfRepository.cs
> +        var newValue = await _dbContext.Set<News>().AddAsync(news);
Добавил еще один комментарий по поводу инжекта ДбКонтекста (в Program.cs)
И получается инжектить лучше сразу конкретный контекст, потому что потом контекстов может быть несколько (например отдельный для авторизации). И тогда уже не получится их инжектить через DbContext

2023-08-22 16:04 UTC, RyT-13 commented on Finik/Finik.EfData/FinikDbContext.cs
> +    {
Пустой метод тоже можно убрать)

2023-08-22 16:05 UTC, bunnysband commented on Finik/Finik.Web/Program.cs
> +builder.Services.AddScoped<DbContext, FinikDbContext>();
fixed

2023-08-22 16:05 UTC, bunnysband commented on Finik/Finik.EfData/FinikDbContext.cs
> +    {
fixed

2023-08-22 16:11 UTC, RyT-13 approved these changes

2023-08-22 16:13 UTC, merged